import = ["/root/.config/alacritty/themes/light.toml"]
live_config_reload = true

[font]
size = 10

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window]
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 0
y = 0
